// minimal service set for Jenfeld client to save us about 7MB
export const services = [
  {
    id: 'anliegen-jenfeld',
    name: 'MML Anliegen (Jenfeld)',
    url: 'https://geodienste.hamburg.de/lgv-config/anliegen_extern_jenfeld.json',
    typ: 'GeoJSON',
    format: 'XML',
    version: '1.0',
    minScale: '0',
    maxScale: '2500000',
    gfiAttributes: 'showAll',
    gfiTheme: 'mml',
    layerAttribution: 'nicht vorhanden',
    legendURL: '',
    datasets: [],
    urlIsVisible: true,
  },
  {
    id: '453',
    name: 'Geobasiskarten (HamburgDE)',
    url: 'https://geodienste.hamburg.de/HH_WMS_HamburgDE',
    typ: 'WMS',
    layers: 'geobasiskarten_hhde',
    format: 'image/png',
    version: '1.3.0',
    singleTile: false,
    transparent: true,
    transparency: 0,
    urlIsVisible: true,
    tilesize: 512,
    gutter: 0,
    minScale: '0',
    maxScale: '2500000',
    gfiAttributes: 'ignore',
    gfiTheme: 'default',
    layerAttribution: 'nicht vorhanden',
    legendURL:
      'https://geodienste.hamburg.de/HH_WMS_HamburgDE?language=ger&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=geobasiskarten_hhde&format=image/png&STYLE=default',
    cache: false,
    featureCount: 1,
    datasets: [
      {
        md_id: 'B6A59A2B-2D40-4676-9094-0EB73039ED34',
        csw_url: 'https://metaver.de/csw',
        show_doc_url:
          'https://metaver.de/trefferanzeige?cmd=doShowDocument&docuuid=',
        rs_id:
          'https://registry.gdi-de.org/id/de.hh/001719df-6619-40b7-aefe-32e8aaf49337',
        md_name: 'GeoBasisKarten Hamburg',
        bbox: '466251.4292773354,5844577.894672247,661887.1257872104,6042030.30978004',
        kategorie_opendata: ['Umwelt'],
        kategorie_inspire: ['kein INSPIRE-Thema'],
        kategorie_organisation: 'Landesbetrieb Geoinformation und Vermessung',
      },
    ],
    notSupportedFor3DNeu: false,
  },
  {
    id: '34127',
    name: 'DOP Zeitreihe belaubt',
    url: 'https://geodienste.hamburg.de/wms_dop_zeitreihe_belaubt',
    typ: 'WMS',
    layers: 'dop_zeitreihe_belaubt',
    format: 'image/png',
    version: '1.3.0',
    singleTile: false,
    transparent: true,
    transparency: 0,
    urlIsVisible: true,
    tilesize: 512,
    gutter: 0,
    minScale: '0',
    maxScale: '2500000',
    gfiAttributes: 'ignore',
    gfiTheme: 'default',
    layerAttribution: 'nicht vorhanden',
    legendURL:
      'https://geodienste.hamburg.de/wms_dop_zeitreihe_belaubt?language=ger&version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=dop_zeitreihe_belaubt&format=image/png&STYLE=default',
    cache: false,
    featureCount: 1,
    datasets: [
      {
        md_id: '5DF0990B-9195-41E7-9960-9214BC85B4DA',
        csw_url: 'https://metaver.de/csw',
        show_doc_url:
          'https://metaver.de/trefferanzeige?cmd=doShowDocument&docuuid=',
        rs_id:
          'https://registry.gdi-de.org/id/de.hh/970151d1-575a-488e-99b6-054039c8f57d',
        md_name: 'Luftbilder Hamburg - DOP Zeitreihe belaubt',
        bbox: '8.420551 53.394985,10.326304 53.964153',
        kategorie_opendata: ['Umwelt'],
        kategorie_inspire: ['Orthofotografie'],
        kategorie_organisation:
          'Landesbetrieb Geoinformation und Vermessung (LGV) Hamburg',
      },
    ],
    notSupportedFor3DNeu: false,
    time: true,
  },
]
