export default [
	{
		id: '23420',
		name: 'basemap.de Web Raster Farbe',
		url: 'https://sgx.geodatenzentrum.de/wms_basemapde',
		typ: 'WMS',
		layers: 'de_basemapde_web_raster_farbe',
		format: 'image/png',
		version: '1.3.0',
		singleTile: false,
		transparent: true,
		transparency: 0,
		urlIsVisible: true,
		tilesize: 512,
		gutter: 0,
		minScale: '0',
		maxScale: '2500000',
		legendURL: '',
		cache: false,
		featureCount: 5,
	},
	{
		id: '23421',
		name: 'basemap.de Web Raster Grau',
		url: 'https://sgx.geodatenzentrum.de/wms_basemapde',
		typ: 'WMS',
		layers: 'de_basemapde_web_raster_grau',
		format: 'image/png',
		version: '1.3.0',
		singleTile: false,
		transparent: true,
		transparency: 0,
		urlIsVisible: true,
		tilesize: 512,
		gutter: 0,
		minScale: '0',
		maxScale: '2500000',
		legendURL: '',
		cache: false,
		featureCount: 5,
	},
	{
		id: '1454',
		name: 'Ausgleichsflächen',
		url: 'https://geodienste.hamburg.de/HH_WFS_Ausgleichsflaechen',
		typ: 'WFS',
		featureType: 'ausgleichsflaechen',
		outputFormat: 'XML',
		version: '1.1.0',
		featureNS: 'https://registry.gdi-de.org/id/de.hh.up',
		featurePrefix: 'de.hh.up',
		legendURL: '',
	},
	{
		id: '6059',
		name: 'MML Anliegen',
		url: 'https://geodienste.hamburg.de/lgv-config/anliegen_extern.json',
		typ: 'GeoJSON',
		format: 'XML',
		version: '1.0',
		minScale: '0',
		maxScale: '2500000',
		legendURL: '',
		urlIsVisible: true,
		clusterDistance: 20,
	},
	{
		id: 'denkmaelerWMS',
		name: 'Denkmal WMS',
		url: 'https://efi2-deegree.schleswig-holstein.de/dish-deegree/services/wms_shp',
		typ: 'WMS',
		layers: '0,1,2,3,4,6,24,25',
		legendURL: 'ignore',
		format: 'image/png',
		version: '1.3.0',
		transparent: true,
	},
	{
		id: '1693',
		name: 'Landesgrenze',
		url: 'https://geodienste.hamburg.de/HH_WFS_Verwaltungsgrenzen',
		typ: 'WFS',
		featureType: 'landesgrenze',
		outputFormat: 'XML',
		version: '1.1.0',
		featureNS: 'http://www.deegree.org/app',
		featurePrefix: 'app',
	},
	{
		id: 'kiel_polygon',
		name: 'Kiel Polygon',
		url: 'https://polar.dataport.de/qgisserver?MAP=/home/qgis/projects/dev_services.qgz',
		typ: 'WFS',
		featureType: 'polygon_kiel',
		outputFormat: 'XML',
		version: '1.1.0',
		legendURL: '',
	},
]
