import type VectorSource from 'ol/source/Vector'

import { debounce } from 'es-toolkit'
import { onWatcherCleanup, ref, type Ref, watch } from 'vue'

/**
 * Generate a reactive value based on the provided callback, which is re-evaluated when any of the provided sources emit a 'change' event.
 * The callback is debounced to prevent excessive re-evaluation.
 *
 * The value is also re-evaluated when the extent changes.
 *
 * @param sources - A ref containing an array of OpenLayers VectorSources to watch for changes.
 * @param reactivitySource - A reactive source to watch for changes, such as the map view, to trigger re-evaluation of the callback when it changes.
 * @param callback - A function that generates the value to be returned.
 * @param waitMs - The debounce delay in milliseconds.
 * @returns A ref containing the reactive value generated by the callback.
 */
export function useOlVectorSources<T>(
	sources: Ref<VectorSource[]>,
	reactivitySource: Ref<unknown>,
	callback: () => T,
	waitMs: number = 50
): Ref<T> {
	const result = ref(callback()) as Ref<T>
	const refresh = () => {
		result.value = callback()
	}
	const debouncedRefresh = debounce(refresh, waitMs)

	watch(
		sources,
		(sources) => {
			refresh()
			sources.forEach((source) => {
				source.on('addfeature', debouncedRefresh)
				source.on('removefeature', debouncedRefresh)
			})
			onWatcherCleanup(() => {
				sources.forEach((source) => {
					source.un('addfeature', debouncedRefresh)
					source.un('removefeature', debouncedRefresh)
				})
			})
		},
		{ deep: true }
	)

	watch(reactivitySource, refresh, { deep: true })

	refresh()
	return result
}
