export const services = [
  {
    id: 'openStreetMap',
    urls: [
      'https://a.tile.openstreetmap.org/{TileMatrix}/{TileCol}/{TileRow}.png',
      'https://b.tile.openstreetmap.org/{TileMatrix}/{TileCol}/{TileRow}.png',
      'https://c.tile.openstreetmap.org/{TileMatrix}/{TileCol}/{TileRow}.png',
    ],
    typ: 'WMTS',
    format: 'image/png',
    coordinateSystem: 'EPSG:3857',
    origin: [-20037508.3428, 20037508.3428],
    transparent: false,
    tileSize: '256',
    minScale: '1',
    maxScale: '2500000',
    tileMatrixSet: 'google3857',
    requestEncoding: 'REST',
    resLength: '20',
  },
  {
    id: 'sentinel2',
    url: 'https://sgx.geodatenzentrum.de/wms_sentinel2_de',
    typ: 'WMS',
    layers: 'rgb_2021',
    legendURL: 'ignore',
    format: 'image/png',
    version: '1.3.0',
    transparent: true,
  },
  {
    id: 'bauplaene',
    name: 'Festgestellte Bebauungspläne (PLIS)',
    url: 'https://geodienste.hamburg.de/HH_WFS_Bebauungsplaene',
    typ: 'WFS',
    featureType: 'hh_hh_festgestellt',
    outputFormat: 'XML',
    version: '1.1.0',
    featureNS: 'http://www.deegree.org/app',
  },
]
